Repository pygame-community/pygame-ce, pull requests merged in 2024-04, with the labels that each got.

#2778 Remove apt upgrade in CI
  .github/workflows/build-ubuntu-sdist.yml
  .github/workflows/cppcheck.yml
Labels: CI

#2772 `python3 setup.py lint` is deprecated: Let's lint with `pre-commit`
  .github/workflows/format-lint.yml
  .pre-commit-config.yaml
Labels: setup.py

#2534 Add SIMD versions of the invert transform
  src_c/simd_transform.h
  src_c/simd_transform_avx2.c
  src_c/simd_transform_sse2.c
  src_c/transform.c
Labels: Performance, SIMD, transform

#2802 (Freetype) use calloc where possible
  src_c/freetype/ft_cache.c
  src_c/freetype/ft_wrap.c
  src_c/freetype/ft_wrap.h
Labels: Code quality/robustness, freetype

#2806 SDL 2.30.2
  buildconfig/download_win_prebuilt.py
  buildconfig/manylinux-build/docker_base/sdl_libs/build-sdl2-libs.sh
  buildconfig/manylinux-build/docker_base/sdl_libs/sdl2.sha512
  meson.build
Labels: dependencies

#2803 Fix sdist to include meson stuff and minor updates
  .github/workflows/build-ubuntu-sdist.yml
  buildconfig/MANIFEST.in
Labels: buildconfig

#2804 Use macros for (Bytes|Bits)PerPixel compat in SDL3
  src_c/SDL_gfx/SDL_gfxPrimitives.c
  src_c/SDL_gfx/SDL_gfxPrimitives.h
  src_c/_camera.c
  src_c/_pygame.h
  src_c/alphablit.c
  src_c/display.c
  src_c/draw.c
  src_c/freetype/ft_render.c
  src_c/freetype/ft_render_cb.c
  src_c/gfxdraw.c
  src_c/image.c
  src_c/mask.c
  src_c/pixelarray.c
  src_c/pixelarray_methods.c
  src_c/pixelcopy.c
  src_c/rotozoom.c
  src_c/scale2x.c
  src_c/simd_blitters_sse2.c
  src_c/surface.c
  src_c/surface_fill.c
  src_c/transform.c
Labels: sdl3

#2779 Add armv6 and armv7 to multiarch CI and fix build issues
  .github/workflows/build-debian-multiarch.yml
  meson.build
  src_c/simd_fill.h
  src_c/simd_shared.h
  src_c/simd_surface_fill_sse2.c
Labels: ARM, CI

#2786 Optimized Rect multi-collision methods
  src_c/rect_impl.h
Labels: Performance, rect

#2771 Minor optimizations by using comprehensions
  buildconfig/config.py
  buildconfig/stubs/gen_stubs.py
  examples/font_viewer.py
  setup.py
  src_py/cursors.py
  src_py/surfarray.py
  src_py/sysfont.py
  test/draw_test.py
  test/event_test.py
  test/font_test.py
  test/mouse_test.py
  test/test_utils/png.py
  test/test_utils/run_tests.py
Labels: Code quality/robustness

#2819 Remove use of Py_BuildValue("(ii)")
  src_c/_camera.c
  src_c/base.c
  src_c/color.c
  src_c/display.c
  src_c/event.c
  src_c/font.c
  src_c/joystick.c
  src_c/key.c
  src_c/mask.c
  src_c/surface.c
  src_c/window.c
Labels: Performance

#2801 Unify freetype init codepaths
  src_c/_freetype.c
Labels: Code quality/robustness, rwops, freetype

#2823 xwayland warning removed; documented; and debug info now contains whether x11 is running or xwayland
  docs/reST/ref/display.rst
  src_c/display.c
  src_py/_debug.py
Labels: docs, Gnu/Linux, display, wayland
