Repository pygame-community/pygame-ce, pull requests merged in 2025-04, with the labels that each got.

#3399 Update dependencies
  buildconfig/download_win_prebuilt.py
  buildconfig/manylinux-build/docker_base/sdl_libs/build-sdl2-libs.sh
  buildconfig/manylinux-build/docker_base/sdl_libs/sdl2.sha512
  meson.build
Labels: dependencies

#3408 Fix `pygame.Vector{2,3}` initialization from numpy arrays
  src_c/math.c
  test/math_test.py
Labels: math, bugfix

#3401 Update to SDL2_image 2.8.8
  buildconfig/download_win_prebuilt.py
  buildconfig/manylinux-build/docker_base/sdl_libs/build-sdl2-libs.sh
  buildconfig/manylinux-build/docker_base/sdl_libs/sdl2.sha512
  meson.build
Labels: dependencies

#3410 Fix `__class_getitem__` to be positional-only
  buildconfig/stubs/pygame/sprite.pyi
Labels: type hints

#3379 Add `Color.hex`
  buildconfig/stubs/pygame/color.pyi
  docs/reST/ref/color.rst
  src_c/color.c
  src_c/doc/color_doc.h
  test/color_test.py
Labels: New API, color

#3351 Get transform compiling on SDL3
  src_c/_pygame.h
  src_c/meson.build
  src_c/simd_transform.h
  src_c/simd_transform_avx2.c
  src_c/simd_transform_sse2.c
  src_c/transform.c
Labels: transform, sdl3

#3418 Remove controller.c from gitignore
  .gitignore
Labels: Code quality/robustness
