Repository pygame-community/pygame-ce, pull requests merged in 2025-09, with the labels that each got.

#3580 [Part 5] SDL3: image+scrap+transform+debug: runtime fixes
  src_c/image.c
  src_c/scrap.c
  src_c/scrap_sdl2.c
  src_c/transform.c
  src_py/_debug.py
Labels: sdl3

#3573 Fix PG_SURF_BitsPerPixel SDL3
  src_c/_pygame.h
Labels: Surface, sdl3

#3590 Add weak reference support to Texture
  src_c/include/_pygame.h
  src_c/render.c
  test/render_test.py
Labels: _render
